//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class GuestComment
    {
        #region "GuestComments"
        public short Id { get; set; }

        [Required]
        [RegularExpression("([a-zA-Z .&'-]+)", ErrorMessage = "Enter only alphabets ")]
        public string Name { get; set; }

        [Required]
        public string Comments { get; set; }
        #endregion
    }
}
