//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6.Models
{
    using System;

    #region "GuestDetails"
    public partial class GuestDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public Nullable<int> InvitationId { get; set; }
        public Nullable<System.DateTime> DateOFBirth { get; set; }
        public string Gender { get; set; }
    }
    #endregion
}
