//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment9.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class tblDepartment
    {
        #region "Department"
        public short Id { get; set; }

        [Required]
        [RegularExpression("([a-zA-Z .&'-]+)", ErrorMessage = "Enter only alphabets ")]
        public string Department { get; set; }

        [Required]
        public string Location { get; set; }

        [Required]
        [RegularExpression("^[0-9]{1,12}$", ErrorMessage = "Age must be numeric")]
        public int TotalEmployee { get; set; }
        #endregion
    }
}
