//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.Models
{
    using System.Collections.Generic;

    public partial class Invitation
    {
        #region "Invitation Model"
        public Invitation()
        {
            this.Guests = new HashSet<Guest>();
        }

        public int InvitationId { get; set; }
        public string Invited { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        #endregion
    }
}
