//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment11.Models
{
    using Assignment11.Common;
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class GuestDetail
    {
        #region "GuestDetails"
        public int Id { get; set; }

        [Required]
        [RegularExpression("([a-zA-Z .&'-]+)", ErrorMessage = "Enter only alphabets ")]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Please Provide Valid Email")]
        [RemoteClientServer("IsEmailAvailable","GuestDetails",ErrorMessage = "Email already in use.")]
        public string Email { get; set; }

        [Required]
        [RegularExpression("^[0-9]{1,12}$", ErrorMessage = "Age must be numeric")]
        [Range(1,100)]
        public int Age { get; set; }

        [Required]
        [Display(Name="Invitation")]
        public Nullable<int> InvitationId { get; set; }

        [Required]
        [Display(Name ="Date Of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> DateOFBirth { get; set; }

        [Required]
        public string Gender { get; set; }
    
        public virtual Invitation Invitation { get; set; }
        #endregion
    }
}
